/**
 * Calibration tests — Nelder-Mead recovers a known parameter from a
 * reference series generated by that exact same model.
 */

import { describe, expect, it } from 'vitest';

import { compile } from '../src/api/compile.js';
import { parse } from '../src/api/parse.js';
import { runCalibration } from '../src/runtime/calibrate.js';

function compileFor(src: string) {
  const { ast, diagnostics: parseDiags } = parse(src);
  expect(parseDiags.filter((d) => d.severity === 'error')).toEqual([]);
  const { program, diagnostics } = compile(ast);
  expect(diagnostics.filter((d) => d.severity === 'error')).toEqual([]);
  return program;
}

describe('runCalibration', () => {
  it('recovers a known exponential growth rate within tolerance', () => {
    // Reference points were generated from rate = 0.10 (Population(t) = 100·e^(0.1t)).
    // Default `rate = 0.05` is wrong on purpose; calibration must move it toward 0.10.
    const program = compileFor(
      [
        'StartTime = 0',
        'EndTime = 20',
        'TimeStep = 0.5',
        'constant rate = 0.05',
        'stock Population = 100',
        'flow Growth:',
        '    Population * rate -+> Population',
        'reference Population:',
        '    (0, 100)',
        '    (5, 164.87)',
        '    (10, 271.83)',
        '    (15, 448.17)',
        '    (20, 738.91)',
        'calibrate:',
        '    bounds rate = [0.0, 0.5]',
        '',
      ].join('\n'),
    );
    const r = runCalibration(program, { maxIterations: 200 });
    expect(r.status).toBe('ok');
    if (r.status === 'ok') {
      expect(r.params).toHaveLength(1);
      const fitted = r.params[0]!.fitted;
      // Allow a generous tolerance; on this 5-point reference the optimum
      // sits right around 0.10.
      expect(fitted).toBeGreaterThan(0.095);
      expect(fitted).toBeLessThan(0.105);
      expect(r.finalCost).toBeLessThan(r.initialCost);
      expect(r.finalCost).toBeLessThan(2.0); // RMSE essentially noise-level
    }
  });

  it('returns an error when no calibrate block is declared', () => {
    const program = compileFor(['stock A = 0', ''].join('\n'));
    const r = runCalibration(program);
    expect(r.status).toBe('error');
  });

  it('returns an error when no reference modes are declared', () => {
    const program = compileFor(
      [
        'constant rate = 0.05',
        'stock Population = 100',
        'flow Growth:',
        '    Population * rate -+> Population',
        'calibrate:',
        '    bounds rate = [0.0, 0.5]',
        '',
      ].join('\n'),
    );
    const r = runCalibration(program);
    expect(r.status).toBe('error');
  });

  it('handles two-parameter calibration on a logistic model', () => {
    // Reference targets derived from BirthRate=0.20, CarryingCapacity=800.
    // Defaults are far off; both should be recovered.
    const program = compileFor(
      [
        'StartTime = 0',
        'EndTime = 30',
        'TimeStep = 0.5',
        'constant BirthRate = 0.05',
        'constant CarryingCapacity = 200',
        'stock Population = 50',
        'calc Pressure = Population / CarryingCapacity',
        'flow Births:',
        '    Population * BirthRate * (1 - Pressure) -+> Population',
        'reference Population:',
        '    (0, 50)',
        '    (5, 110)',
        '    (10, 220)',
        '    (15, 400)',
        '    (20, 600)',
        '    (25, 730)',
        '    (30, 780)',
        'calibrate:',
        '    bounds BirthRate = [0.01, 0.5]',
        '    bounds CarryingCapacity = [100, 2000]',
        '',
      ].join('\n'),
    );
    const r = runCalibration(program, { maxIterations: 400 });
    expect(r.status).toBe('ok');
    if (r.status === 'ok') {
      expect(r.params).toHaveLength(2);
      // Cost should drop substantially — the exact optimum depends on the
      // numeric integration, so we assert improvement rather than absolute fit.
      expect(r.finalCost).toBeLessThan(r.initialCost / 5);
    }
  });
});
